@include("include.form.input.date",['required'=> true, 'id'=>'agreement_date', 'name'=>'Agreement Date'])
@include("include.form.input.select",['required'=> true, 'id'=>'template_id','name'=>'Agreement Model', 'values'=> $templates->pluck('name','id')->prepend('select', '') ])
@include("include.form.input.select",['required'=> true, 'id'=>'first_owner_id','name'=>'First Owner', 'values'=> $owners->pluck('name','id')->prepend('select', '') ])
@include("include.form.input.select",['id'=>'second_owner_id','name'=>'Second Owner', 'values'=> $owners->pluck('name','id')->prepend('select', '') ])
@include("include.form.input.select",['required'=> true, 'id'=>'first_buyer_id','name'=>'First Buyer', 'values'=> $contacts->pluck('name','id')->prepend('select', '') ])
@include("include.form.input.select",['id'=>'second_buyer_id','name'=>'Second Buyer', 'values'=> $contacts->pluck('name','id')->prepend('select', '') ])
@include("include.form.input.date",['required'=> true, 'id'=>'initial_renting_date', 'name'=>'Limit date title land granting'])
@include("include.form.input.number",['required'=> true, 'icon'=>'&euro;', 'id'=>'down_payment_amount', 'name'=>'Down payment amount'])
@include("include.form.input.number",['required'=> true,  'icon'=>'&euro;', 'id'=>'down_payment_amount_spelled', 'name'=>'Down payment amount spelled out'])
@include("include.form.input.number",['required'=> true,  'icon'=>'&euro;', 'id'=>'full_selling_amount', 'name'=>'Full selling amount'])
@include("include.form.input.number",['required'=> true,  'icon'=>'&euro;', 'id'=>'full_selling_amount_spelled', 'name'=>'Full selling amount spelled'])
@include("include.form.input.number",['required'=> true,  'icon'=>'&euro;', 'id'=>'remaining_selling_amount', 'name'=>'Remaining selling amount'])
@include("include.form.input.number",['required'=> true,  'icon'=>'&euro;', 'id'=>'remaining_selling_amount_spelled', 'name'=>'Remaining selling amount spelled out'])