@include("include.form.input.date",['required'=> true, 'id'=>'agreement_date', 'name'=>'Agreement Date'])
@include("include.form.input.select",['required'=> true, 'id'=>'agreement_time','name'=>'Agreement Time', 'values'=> $hours])
@include("include.form.input.select",['required'=> true, 'id'=>'template_id','name'=>'Agreement Model', 'values'=> $templates->pluck('name','id')->prepend('select', '') ])
@include("include.form.input.select",['required'=> true, 'id'=>'visitor_id','name'=>'Visitor', 'values'=> $contacts->pluck('name', 'id')->prepend('select','') ])
@include("include.form.input.select",['required'=> true, 'id'=>'comercial_id','name'=>'Comercial', 'values'=> $users->pluck('name', 'id')->prepend('select','') ])